CREATE TABLE employee (
    id UUID NOT NULL,
    version BIGINT NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    zip_code VARCHAR(255),
    country VARCHAR(255),
    contact_number VARCHAR(255),
    email_address VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE project (
    id UUID NOT NULL,
    version BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    PRIMARY KEY (id),
    CONSTRAINT uk_project_name UNIQUE (name)
);

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    project_id UUID NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_task_project_name UNIQUE (project_id, name),
    CONSTRAINT fk_task_project FOREIGN KEY (project_id) REFERENCES project (id)
);

CREATE TABLE "leave" (
    id UUID NOT NULL,
    version BIGINT NOT NULL,
    start_date DATE,
    end_date DATE,
    type VARCHAR(255),
    status VARCHAR(255),
    reason VARCHAR(255),
    hours DOUBLE PRECISION NOT NULL,
    comments VARCHAR(255),
    employee_id UUID NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_leave_employee FOREIGN KEY (employee_id) REFERENCES employee (id)
);

CREATE TABLE timesheet (
    id UUID NOT NULL,
    version BIGINT NOT NULL,
    status VARCHAR(255),
    start_date DATE,
    end_date DATE,
    employee_id UUID NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_timesheet_employee_period UNIQUE (employee_id, start_date, end_date),
    CONSTRAINT fk_timesheet_employee FOREIGN KEY (employee_id) REFERENCES employee (id)
);

CREATE TABLE timesheet_entry (
    id UUID NOT NULL,
    date DATE,
    entry_type VARCHAR(255),
    hours DOUBLE PRECISION NOT NULL,
    disable BOOLEAN NOT NULL,
    task_id BIGINT,
    timesheet_id UUID NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_timesheet_entry_task FOREIGN KEY (task_id) REFERENCES task (id),
    CONSTRAINT fk_timesheet_entry_timesheet FOREIGN KEY (timesheet_id) REFERENCES timesheet (id)
);

CREATE TABLE timesheet_approval (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    approval_date DATE,
    status VARCHAR(255),
    comments VARCHAR(255),
    approver_id UUID NOT NULL,
    timesheet_id UUID NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_timesheet_approval_approver FOREIGN KEY (approver_id) REFERENCES employee (id),
    CONSTRAINT fk_timesheet_approval_timesheet FOREIGN KEY (timesheet_id) REFERENCES timesheet (id)
);

CREATE TABLE leave_approval (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status VARCHAR(255),
    comments VARCHAR(255),
    decision_date DATE,
    approver_id UUID NOT NULL,
    leave_id UUID NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_leave_approval_approver FOREIGN KEY (approver_id) REFERENCES employee (id),
    CONSTRAINT fk_leave_approval_leave FOREIGN KEY (leave_id) REFERENCES "leave" (id)
);

CREATE TABLE holiday (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    date DATE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_holiday_date UNIQUE (date)
);

CREATE TABLE employee_manager (
    employee_id UUID NOT NULL,
    manager_id UUID,
    PRIMARY KEY (employee_id),
    CONSTRAINT fk_employee_manager_employee FOREIGN KEY (employee_id) REFERENCES employee (id),
    CONSTRAINT fk_employee_manager_manager FOREIGN KEY (manager_id) REFERENCES employee (id)
);

CREATE TABLE project_employee (
    project_id UUID NOT NULL,
    employees_id UUID NOT NULL,
    PRIMARY KEY (project_id, employees_id),
    CONSTRAINT fk_project_employee_project FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT fk_project_employee_employee FOREIGN KEY (employees_id) REFERENCES employee (id)
);

CREATE TABLE task_employee (
    task_id BIGINT NOT NULL,
    employees_id UUID NOT NULL,
    PRIMARY KEY (task_id, employees_id),
    CONSTRAINT fk_task_employee_task FOREIGN KEY (task_id) REFERENCES task (id),
    CONSTRAINT fk_task_employee_employee FOREIGN KEY (employees_id) REFERENCES employee (id)
);

CREATE INDEX idx_leave_employee_id ON "leave" (employee_id);
CREATE INDEX idx_timesheet_entry_timesheet_id ON timesheet_entry (timesheet_id);
CREATE INDEX idx_timesheet_entry_task_id ON timesheet_entry (task_id);
CREATE INDEX idx_timesheet_approval_timesheet_id ON timesheet_approval (timesheet_id);
CREATE INDEX idx_leave_approval_leave_id ON leave_approval (leave_id);

